config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root "wines#new"
  resources :wines
  resources :assemblies
  resources :strains
  resources :enologists
  resources :magazines
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/assembly.rb
class Assembly < ApplicationRecord
  belongs_to :wine
  belongs_to :strain
  def strain_name
    strain&.name
  end
end

app/models/enologist.rb
class Enologist < ApplicationRecord

  has_many :positions
  has_many :magazines, through: :positions

  has_many :grades
  has_many :wines, through: :grades

end

app/models/grade.rb
class Grade < ApplicationRecord
  belongs_to :wine
  belongs_to :enologist
end

app/models/magazine.rb
class Magazine < ApplicationRecord

  has_many :positions
  has_many :enologists, through: :positions

end

app/models/position.rb
class Position < ApplicationRecord
  belongs_to :enologist
  belongs_to :magazine
end

app/models/strain.rb
class Strain < ApplicationRecord
  has_many :assemblies
  has_many :wines, through: :assemblies
  validates :name, presence: true
  enum avaliable: [:no_available, :available] 
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/wine.rb
class Wine < ApplicationRecord
  has_many :assemblies
  has_many :strains, through: :assemblies
  has_many :grades
  has_many :enologists, through: :grades
  accepts_nested_attributes_for :assemblies

  def strains_detail
    detail=assemblies.map do |assembly|
      "#{assembly.strain_name} (#{assembly.percentage}%)"
    end
    detail.join(', ')
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
end

app/controllers/assemblies_controller.rb
class AssembliesController < ApplicationController
  
  before_action :set_assambly, only: [:show, :edit, :update, :destroy]

  def new
  end

  def show
  end

  def create
  end

  def index
  end

  def edit
  end

  def update
  end

  def destroy
  end

 private

  def set_assembly
	  @wine=Wine.find(params[:id])
  end

  def assembly_params		
    params.require(:wine).permit(:name, :price)
  end

end

app/controllers/enologists_controller.rb
class EnologistsController < ApplicationController
  
  before_action :set_enologist, only: [:show, :edit, :update, :destroy]

  def new
  end

  def show
  end

  def create
  end

  def index
  end

  def edit
  end

  def update
  end

  def destroy
  end

  private

  def set_enologist
	  @wine=Wine.find(params[:id])
  end

  def enologist_params		
    params.require(:wine).permit(:name, :price)
  end

end

app/controllers/magazines_controller.rb
class MagazinesController < ApplicationController
  
  before_action :set_magazine, only: [:show, :edit, :update, :destroy]

  def new
  end

  def show
  end

  def create
  end

  def index
  end

  def edit
  end

  def update
  end

  def destroy
  end

  private

  def set_magazine
	  @wine=Wine.find(params[:id])
  end

  def magazine_params		
    params.require(:wine).permit(:name, :price)
  end

end

app/controllers/strains_controller.rb
class StrainsController < ApplicationController
  
  before_action :set_strain, only: [:show, :edit, :update, :destroy]

  def new
    redirect_to wines_path unless current_user&.admin?
    @strain=Strain.new
  end

  def show
  end

  def create
  
    @strain=Strain.new(strain_params)
    if @strain.save
      flash[:notice]="Cepa creada exitosamente"
      redirect_to new_strain_path
    else
      flash[:danger]="Ups! ocurrió un error"
      render :new
    end


  end

  def index
  end

  def edit
  end

  def update
  end

  def destroy
  end

  private

  def set_strain
	  @strain=strain.find(params[:id])
  end

  def strain_params		
    params.require(:strain).permit(:name, :price)
  end

end

app/controllers/wines_controller.rb
class WinesController < ApplicationController
  
  before_action :set_wine, only: [:show, :edit, :update, :destroy]
  def new
    redirect_to wines_path unless current_user&.admin?
    @wine=Wine.new
    @strains=Strain.all
    @strains.each do |strain|
      @wine.assemblies.build(strain: strain)
    end
  end

  def show
  end

  def create

    @wine=Wine.new(wine_params)
    if @wine.save
      flash[:notice]="Vino creado exitosamente"
      redirect_to wines_path
    else
      flash[:danger]="Ups! ocurrió un error"
      render :new
    end

  end

  def index
    @wines=Wine.all
  end

  def edit
  end

  def update
  end

  def destroy
  end

 private

  def set_wine
	  @wine=Wine.find(params[:id])
  end

  def wine_params		
    params.require(:wine).permit(:name, :price, assemblies_attributes: [:id, :strain_id, :wine_id, :percentage])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/enologists_helper.rb
module EnologistsHelper
end

app/helpers/magazines_helper.rb
module MagazinesHelper
end

app/helpers/strains_helper.rb
module StrainsHelper
end

app/helpers/wines_helper.rb
module WinesHelper
end

app/views/enologists/create.html.erb
<h1>Enologists#create</h1>
<p>Find me in app/views/enologists/create.html.erb</p>

app/views/enologists/destroy.html.erb
<h1>Enologists#destroy</h1>
<p>Find me in app/views/enologists/destroy.html.erb</p>

app/views/enologists/edit.html.erb
<h1>Enologists#edit</h1>
<p>Find me in app/views/enologists/edit.html.erb</p>

app/views/enologists/index.html.erb
<h1>Enologists#index</h1>
<p>Find me in app/views/enologists/index.html.erb</p>

app/views/enologists/new.html.erb
<h1>Enologists#new</h1>
<p>Find me in app/views/enologists/new.html.erb</p>

app/views/enologists/update.html.erb
<h1>Enologists#update</h1>
<p>Find me in app/views/enologists/update.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Cepas1</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>

    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ho+j7jyWK8fNQe+A12Hb8AhRq26LrZ/JpcUGGOn+Y7RsweNrtN/tE3MoK7ZeZDyx" crossorigin="anonymous"></script>

  </head>

  <body>
    <%= render "shared/navbar" %>
    <% flash.each do |type, msg| %>
			<div class="alert alert-<%= type %>
				<%= msg %>
			</div>
		<% end %>
    <%= yield %>
  </body>
</html>

app/views/magazines/create.html.erb
<h1>Magazines#create</h1>
<p>Find me in app/views/magazines/create.html.erb</p>

app/views/magazines/destroy.html.erb
<h1>Magazines#destroy</h1>
<p>Find me in app/views/magazines/destroy.html.erb</p>

app/views/magazines/edit.html.erb
<h1>Magazines#edit</h1>
<p>Find me in app/views/magazines/edit.html.erb</p>

app/views/magazines/index.html.erb
<h1>Magazines#index</h1>
<p>Find me in app/views/magazines/index.html.erb</p>

app/views/magazines/new.html.erb
<h1>Magazines#new</h1>
<p>Find me in app/views/magazines/new.html.erb</p>

app/views/magazines/update.html.erb
<h1>Magazines#update</h1>
<p>Find me in app/views/magazines/update.html.erb</p>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="#">Navbar</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNav">
    <ul class="navbar-nav">
      <li class="nav-item active">
        <a class="nav-link" href="#">Home <span class="sr-only">(current)</span></a>
      </li>
      <%if current_user&.admin? %>
        <li class="nav-item">
          <%=link_to 'Agregar Cepa', new_strain_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%=link_to 'Crear Vino', new_wine_path, class: "nav-link" %>
        </li>
      <% end %>
      <li class="nav-item">
        <a class="nav-link disabled" href="#" tabindex="-1" aria-disabled="true">Disabled</a>
      </li>
      <% if user_signed_in? %>
        <li class="nav-item active">
          <%= link_to 'Cerrar Sesión', destroy_user_session_path(current_ser), method: :delete, class: "nav-link" %>
        </li>
	    <%else%>
        <li class="nav-item">
          <%= link_to 'Iniciar Sesión', new_user_session_path, class: "nav-link"%>
        </li>
        <li class="nav-item">
          <%= link_to 'Registrarse', new_user_registration_path, class: "nav-link" %>
        </li>
	    <% end %>
    </ul>
  </div>
</nav>

app/views/strains/_form.html.erb
<div class="col-4 offset-4">
  <%= form_with(model: strain, local: true) do |form| %>

    <div class="form-group">
      <%= form.label :name, class: "control-label" %>
      <%= form.text_field :name, class: "form-control" %>
    </div>
    <div class="field">
      <%= form.label :available %>
      <%= form.select :available ,Strain.avaliables %>
    </div>

    <div class="actions">
      <%= form.submit "Save", class: "btn btn-success" %>
    </div>

  <% end %>
</div> 

app/views/strains/create.html.erb
<h1>Strains#create</h1>
<p>Find me in app/views/strains/create.html.erb</p>

app/views/strains/destroy.html.erb
<h1>Strains#destroy</h1>
<p>Find me in app/views/strains/destroy.html.erb</p>

app/views/strains/edit.html.erb
<h1>Strains#edit</h1>
<p>Find me in app/views/strains/edit.html.erb</p>

app/views/strains/index.html.erb
<h1>Strains#index</h1>
<p>Find me in app/views/strains/index.html.erb</p>

app/views/strains/new.html.erb
<h1>Strains#new</h1>
<p>Find me in app/views/strains/new.html.erb</p>
<div class="row">
  <%= render 'form', strain: @strain %>
</div>

app/views/strains/update.html.erb
<h1>Strains#update</h1>
<p>Find me in app/views/strains/update.html.erb</p>

app/views/wines/_form.html.erb
<div class="col-4 offset-4">
  <h1>Crear Vino</h1>
  <%= form_with(model: wine, local: true) do |form| %>
    <% if wine.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(wine.errors.count, "error") %> prohibited this wine from being saved:</h2>
        <ul>
          <% wine.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>
    <div class="form-group">
      <%= form.label :name, class: "control-label" %>
      <%= form.text_field :name, class: "form-control" %>
    </div>
    <div class="form-group">
      <%= form.label :price, class: "control-label" %>
      <%= form.number_field :price, class: "form-control" %>
    </div>
    <div class="form-group">
    <%=form.fields_for :assemblies do |assemby_form|%>
      <%= assemby_form.label assemby_form&.object&.strain_name, class:"control-label"%>
      <%=assemby_form.hidden_field :strain_id %>
       <%= assemby_form.number_field :percentage, class:"form-control"%>
    <% end %>
    </div>
    <div class="actions">
      <%= form.submit "Save", class: "btn btn-success" %>
    </div>
  <% end %>
</div>

app/views/wines/create.html.erb
<h1>Wines#create</h1>
<p>Find me in app/views/wines/create.html.erb</p>

app/views/wines/destroy.html.erb
<h1>Wines#destroy</h1>
<p>Find me in app/views/wines/destroy.html.erb</p>

app/views/wines/edit.html.erb
<h1>Wines#edit</h1>
<p>Find me in app/views/wines/edit.html.erb</p>

app/views/wines/index.html.erb
<h1>Wines#index</h1>
<p>Find me in app/views/wines/index.html.erb</p>
<h1>Lista de Vinos</h1>

<table class="table">

  <thead>
    <tr>
      <th>Nombre</th>
      <th>Precio</th>
      <th>Cepas</th>
      <th colspan>"3"></th>
    </tr>
  </thead>

  <tbody>
    <% @wines.each do |wine| %>
      <tr>
        <td><%= wine.name %></td>
        <td><%= wine.price %></td>
        <td><%= wine.strains_detail %></td>
        <% if current_user&.admin? %>
          <td><%= link_to 'Show', wine %></td>
          <td><%= link_to 'Edit', edit_wine_path(wine) %></td>
          <td><%= link_to 'Destroy', wine, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New wine', new_wine_path %>

app/views/wines/new.html.erb
<h1>Wines#new</h1>
<p>Find me in app/views/wines/new.html.erb</p>

<div class="row">
  <%= render 'form', wine: @wine %>
</div>

app/views/wines/show.html.erb
<h1>Show</h1>

app/views/wines/update.html.erb
<h1>Wines#update</h1>
<p>Find me in app/views/wines/update.html.erb</p>